[package]
name = "neuro_assimilator_rust_integration"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"

[lib]
crate-type = ["cdylib"]